# TODO: insert license

# TODO: check tasks below

- name: include release specific variables
  include_vars: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "../vars"
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: crowd

- name: include release specific tasks
  include_tasks: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "."
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: crowd

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ crowd_catalina }}", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0755", state: "directory" }
    - { dest: "{{ crowd_home }}", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0755", state: "directory" }
  tags: crowd

- name: unarchive package
  shell: |
    ARCHIVE="`mktemp --suffix=tar.gz`"
    curl -sL {{ crowd_url }} > $ARCHIVE
    tar zxf $ARCHIVE -C {{ crowd_catalina }} --strip-components=1
    chown -Rf {{ crowd_owner }}:{{ crowd_group }} {{ crowd_catalina }}
    rm -rf $ARCHIVE
  args:
    creates: "{{ crowd_catalina }}/start_crowd.sh"
  tags: crowd

- name: remove stuff due to custom context path
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ crowd_catalina }}/apache-tomcat/webapps/ROOT", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0755", state: "absent" }
    - { dest: "{{ crowd_catalina }}/apache-tomcat/conf/Catalina/localhost/crowd.xml", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0644", state: "absent" }
  tags: crowd

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "opt/atlassian/crowd/build.properties.j2", dest: "{{ crowd_catalina }}/build.properties", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0644" }
  register: build_properties_result
  tags: crowd

- name: update build with ant
  shell: |
    cd {{ crowd_catalina }}
    ./build.sh
    chown -Rf {{ crowd_owner }}:{{ crowd_group }} {{ crowd_catalina }}
  when: build_properties_result.changed
  register: build_result
  changed_when: build_result.rc != 0
  tags: crowd

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/crowd.j2", dest: "/etc/init.d/crowd", owner: "root", group: "root", mode: "0755" }
    - { src: "opt/atlassian/crowd/apache-tomcat/bin/setenv.sh.j2", dest: "{{ crowd_catalina }}/apache-tomcat/bin/setenv.sh", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0755" }
    - { src: "opt/atlassian/crowd/apache-tomcat/conf/server.xml.j2", dest: "{{ crowd_catalina }}/apache-tomcat/conf/server.xml", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0644" }
    - { src: "opt/atlassian/crowd/start_crowd.sh.j2", dest: "{{ crowd_catalina }}/start_crowd.sh", owner: "{{ crowd_owner }}", group: "{{ crowd_group }}", mode: "0755" }
  tags: crowd

- name: enable service
  service:
    name: "crowd"
    enabled: "yes"
  tags: crowd